apiVersion: v1
kind: Service
metadata:
  name: apicertificado
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apicertificado
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
